### ISSUE TITLE
Licensing concern about one of your files

### ISSUE THREAD

**Issue by vladfrangu** [jay3332/js-cord#10]
Hello!

I'm Vlad, one of the owners of [`Sapphire`](https://github.com/sapphiredev). It was brought to our attention that one of the files in this repository (https://github.com/jay3332/js-cord/blob/rewrite/js-cord/core/Queue.js) is a 1:1 copy of our already published module `@sapphire/async-queue` (with it's source code located at https://github.com/sapphiredev/utilities/blob/main/packages/async-queue/src/lib/AsyncQueue.ts, where your code has extremely minor changes like removing documentation). 

We'd like to ask you kindly to either use our module (`npm i @sapphire/async-queue`), or add the appropriate license header (either in a `THIRD_PARTY_LICENSES.md` file, a license header comment at the top of the Queue.js file, or in the repository's `LICENSE.md` file). The license itself is available at https://github.com/sapphiredev/utilities/blob/main/LICENSE.md, and applies to all packages, including `async-queue`.

If you have any other questions, please feel free to ask them! 

Thanks,
Vlad.

**Comment by jay3332** [comment]
Completely forgot about this, will add it right now. Thanks for bringing this up

**Comment by jay3332** [comment]
https://github.com/jay3332/js-cord/blob/rewrite/js-cord/core/Queue.js

**Comment by kyranet** [comment]
Thanks for taking care of the license.

However, it's not fully compliant to MIT License's requirements (which is to include the \*full* license), the title ("MIT License") and the authors are missing.

As a side note, the queue's code might be hard for you and/or your team to maintain, and might be misunderstood in the future, is there a reason why did you decide to not use the module?

Also, this repository doesn't have a LICENSE.md file, which legally forbids anyone but you from distributing and using the code.

**Comment by jay3332** [comment]
I didn't want to have too many dependencies. Adding a license file right now.
