### ISSUE TITLE
where troll

### ISSUE THREAD

**Issue by Clammerz** [jay3332/js-cord#2]
https://i.imgur.com/TEMCPUu.jpg

**Comment by jay3332** [comment]
i dont know

**Comment by Cats3153** [comment]
smh

**Comment by jay3332** [comment]
s

**Comment by gothpuke** [comment]
I definitely wanted an email for this

**Comment by jay3332** [comment]
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ###
