### ISSUE TITLE
Documentation is completely empty.

### ISSUE THREAD

**Issue by Cats3153** [jay3332/js-cord#6]
![smh](https://user-images.githubusercontent.com/67523849/119911241-c5444d80-bf0d-11eb-8cdf-28e1346daacb.png)

**Comment by jay3332** [comment]
Because docs still point to __master/docs__

**Comment by jay3332** [comment]
I partially fixed this, a lot of the documentation isn't showing htough

**Comment by drapespy** [comment]
Use `?tag jay lies` in [the discord.py server](https://discord.gg/dpy) for a funni!!!!!!

**Comment by jay3332** [comment]
Fixed. You can now view the documentation [here](https://jay3332.github.io/js-cord)
